spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=BATCH_
spring.batch.job.enabled=true

# ????????? ??? SQL ??? ?????? ??????????
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-all.sql
spring.sql.init.continue-on-error=true

# ????????? JPA DDL, ??????? ??????? ????
spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchprocessing=DEBUG