spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=BATCH_
spring.batch.job.enabled=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-all.sql
spring.sql.init.continue-on-error=true

spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchprocessing=DEBUG
logging.level.com.ivanfranchin.moviesapi=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.tags.application=stock-etl-batch
management.metrics.tags.environment=local
management.metrics.distribution.percentiles-histogram.spring.batch.job=true
management.metrics.distribution.percentiles-histogram.spring.batch.step=true

pushgateway.url=http://pushgateway:9091