input {
	beats {
		port => 5044
    	host => "0.0.0.0"
	}
}

filter {
	mutate {
		add_field => {
			"application" => "stock-etl-batch"
			"environment" => "local"
		}
	}
}

output {
	elasticsearch {
		hosts => ["http://elasticsearch:9200"]
    	index => "stock-etl-logs-%{+YYYY.MM.dd}"
    	manage_template => false
	}

	stdout {
		codec => rubydebug
	}
}